import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import WhatsAppButton from "./components/whatsapp";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-white font-outfit`}
      >
        <Navbar/>
        <div className="mt-16 max-w-screen-2xl mx-auto">
          {children}
        </div>
        <WhatsAppButton/>
        <Footer/>
      </body>
    </html>
  );
}
