import type { Metadata } from "next";
import { Outfit } from "@next/font/google"; // Importa la fuente desde @next/font/google
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import WhatsAppButton from "./components/whatsapp";

// Configura la fuente Outfit
const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '700'], // Opcional: define los pesos que necesitas
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={outfit.className}> {/* Aplica la clase de Outfit */}
      <body className="antialiased bg-white">
        <Navbar />
        <div className="mt-16 mx-auto max-w-screen-2xl">
          {children}
        </div>
        <WhatsAppButton />
        <Footer />
      </body>
    </html>
  );
}
